### ISSUE TITLE
ubuntu 12.04 compile errors

### ISSUE THREAD

**Issue by neubi4** [lwille/node-gphoto2#21]
Hello lwille,

i get this errors trying to compile on ubuntu 12.04

```
node-waf configure build
Checking for program g++ or c++          : clang
Checking for program cpp                 : /usr/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for g++                         : ok
Checking for node path                   : not found
Checking for node prefix                 : ok /usr/local
Checking for libgphoto2                  : yes
Checking for libgphoto2_port             : yes
'configure' finished successfully (0.144s)
Waf: Entering directory `/var/www/lapseberry/node_modules/gphoto2/build'
[1/9] cxx: src/preview.cc -> build/Release/src/preview_1.o
[2/9] cxx: src/camera_helpers.cc -> build/Release/src/camera_helpers_2.o
../src/preview.cc:11:13: error: use of undeclared identifier 'stdout'
  fprintf  (stdout, "\n");
            ^
../src/preview.cc:12:13: error: use of undeclared identifier 'stdout'
  fprintf  (stdout, "*** Contexterror ***              \n");
            ^
../src/preview.cc:13:13: error: use of undeclared identifier 'stdout'
  vfprintf (stdout, format, args);
            ^
../src/preview.cc:14:13: error: use of undeclared identifier 'stdout'
  fprintf  (stdout, "data:%p\n", data);
            ^
../src/preview.cc:15:13: error: use of undeclared identifier 'stdout'
  fflush   (stdout);
            ^
../src/preview.cc:55:9: error: use of undeclared identifier 'printf'; did you mean 'wprintf'?
        printf("|");
        ^~~~~~
        wprintf
/usr/include/wchar.h:598:12: note: 'wprintf' declared here
extern int wprintf (__const wchar_t *__restrict __format, ...)
           ^
../src/preview.cc:55:16: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char [2]'
        printf("|");
               ^~~
/usr/include/wchar.h:598:49: note: passing argument to parameter '__format' here
extern int wprintf (__const wchar_t *__restrict __format, ...)
                                                ^
../src/preview.cc:57:7: error: use of undeclared identifier 'printf'; did you mean 'wprintf'?
      printf("\n%.02f%%\n%d fps\033[2A\r",i/20000.0*100.0, cnt);
      ^~~~~~
      wprintf
/usr/include/wchar.h:598:12: note: 'wprintf' declared here
extern int wprintf (__const wchar_t *__restrict __format, ...)
           ^
../src/preview.cc:57:14: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char [21]'
      printf("\n%.02f%%\n%d fps\033[2A\r",i/20000.0*100.0, cnt);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wchar.h:598:49: note: passing argument to parameter '__format' here
extern int wprintf (__const wchar_t *__restrict __format, ...)
                                                ^
../src/preview.cc:58:14: error: use of undeclared identifier 'stdout'
      fflush(stdout);
             ^
../src/preview.cc:64:5: error: use of undeclared identifier 'sprintf'
    sprintf(filename, "./frames/frame%.05d.jpg", i);
    ^
../src/preview.cc:68:21: error: use of undeclared identifier 'printf'; did you mean 'wprintf'?
    if(ret< GP_OK){ printf("gp_file_new returned %d\n", ret); break;}
                    ^~~~~~
                    wprintf
/usr/include/wchar.h:598:12: note: 'wprintf' declared here
extern int wprintf (__const wchar_t *__restrict __format, ...)
           ^
../src/preview.cc:68:28: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char [25]'
    if(ret< GP_OK){ printf("gp_file_new returned %d\n", ret); break;}
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wchar.h:598:49: note: passing argument to parameter '__format' here
extern int wprintf (__const wchar_t *__restrict __format, ...)
                                                ^
../src/preview.cc:70:21: error: use of undeclared identifier 'printf'; did you mean 'wprintf'?
    if(ret< GP_OK){ printf("gp_camera_capture_preview returned %d\n", ret); break;}
                    ^~~~~~
                    wprintf
/usr/include/wchar.h:598:12: note: 'wprintf' declared here
extern int wprintf (__const wchar_t *__restrict __format, ...)
           ^
../src/preview.cc:70:28: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char [39]'
    if(ret< GP_OK){ printf("gp_camera_capture_preview returned %d\n", ret); break;}
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wchar.h:598:49: note: passing argument to parameter '__format' here
extern int wprintf (__const wchar_t *__restrict __format, ...)
                                                ^
../src/preview.cc:72:21: error: use of undeclared identifier 'printf'; did you mean 'wprintf'?
    if(ret< GP_OK){ printf("gp_file_get_data_and_size returned %d\n", ret); break;}
                    ^~~~~~
                    wprintf
/usr/include/wchar.h:598:12: note: 'wprintf' declared here
extern int wprintf (__const wchar_t *__restrict __format, ...)
           ^
../src/preview.cc:72:28: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char [39]'
    if(ret< GP_OK){ printf("gp_file_get_data_and_size returned %d\n", ret); break;}
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/wchar.h:598:49: note: passing argument to parameter '__format' here
extern int wprintf (__const wchar_t *__restrict __format, ...)
                                                ^
../src/preview.cc:80:3: error: use of undeclared identifier 'printf'; did you mean 'wprintf'?
  printf("\n\n\n");
  ^~~~~~
  wprintf
/usr/include/wchar.h:598:12: note: 'wprintf' declared here
extern int wprintf (__const wchar_t *__restrict __format, ...)
           ^
../src/preview.cc:80:10: error: cannot initialize a parameter of type 'const wchar_t *' with an lvalue of type 'const char [4]'
  printf("\n\n\n");
         ^~~~~~~~
/usr/include/wchar.h:598:49: note: passing argument to parameter '__format' here
extern int wprintf (__const wchar_t *__restrict __format, ...)
                                                ^
19 errors generated.
Waf: Leaving directory `/var/www/lapseberry/node_modules/gphoto2/build'
Build failed:  -> task failed (err #1):
        {task: cxx preview.cc -> preview_1.o}
```

Can you help me?
